// Generated by gohack; DO NOT EDIT.
module github.com/divisionone/go-micro

go 1.14

require (
	github.com/divisionone/cli v0.2.1
	github.com/divisionone/go-rcache v0.0.0-20180409064418-3bf8d45e6c93
	github.com/divisionone/util v0.0.0-20180409064546-d45e66572862
	github.com/golang/protobuf v1.3.5
	github.com/hashicorp/consul/api v1.4.0
	github.com/micro/go-log v0.1.0
	github.com/micro/mdns v0.3.0
	github.com/mitchellh/hashstructure v1.0.0
	github.com/pborman/uuid v1.2.0
	github.com/pkg/errors v0.9.1
)
